### ISSUE TITLE
Not able to filter patients using tags

### ISSUE THREAD

**Issue by wabson** [Alfresco/health-care-app#27]
New tags can be added to a patient but selecting a tag does not do anything to the patients list

**Comment by romainguinot** [comment]
tags do not refresh as well when you add one. 

I've also seen this error when adding a tag, but can't reproduce it now. including anyways in case that rings a bell.

```
core.umd.js?e2a5:2843 Error: Failed to execute 'close' on 'HTMLDialogElement': The element does not have an 'open' attribute, and therefore cannot be closed.
    at HTMLButtonElement.eval (eval at 1192 (http://localhost:3000/app.js:197:2), <anonymous>:216:20)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:3000/polyfills.js:3239:2), <anonymous>:265:35)
    at Object.onInvokeTask (eval at <anonymous> (http://localhost:3000/vendor.js:101:2), <anonymous>:5966:41)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:3000/polyfills.js:3239:2), <anonymous>:264:40)
    at Zone.runTask (eval at <anonymous> (http://localhost:3000/polyfills.js:3239:2), <anonymous>:154:47)
    at HTMLButtonElement.ZoneTask.invoke (eval at <anonymous> (http://localhost:3000/polyfills.js:3239:2), <anonymous>:335:33)
  -------------   Elapsed: 1404 ms; At: Wed Feb 15 2017 11:22:30 GMT+0100 (CET)   -------------  
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:3000/polyfills.js:3245:2), <anonymous>:83:18)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:3000/polyfills.js:3239:2), <anonymous>:242:49)
    at Zone.scheduleEventTask (eval at <anonymous> (http://localhost:3000/polyfills.js:3239:2), <anonymous>:174:39)
    at zoneAwareAddListener (eval at <anonymous> (http://localhost:3000/polyfills.js:3239:2), <anonymous>:824:14)
    at HTMLButtonElement.addEventListener (eval at createNamedFn (eval at <anonymous> (http://localhost:3000/polyfills.js:3239:2)), <anonymous>:3:43)
    at PatientsComponent.addTag (eval at 1192 (http://localhost:3000/app.js:197:2), <anonymous>:214:39)
```

**Comment by ghost** [comment]
This repository is now archived and no longer maintained. Closing old issues.
